version: '3.3'

volumes:
  pg_data:
  static:
  static_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: makarochkinia/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: makarochkinia/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
  gateway:
    image: makarochkinia/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
