# Generated by Django 4.2.3 on 2023-07-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newusermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newusermodel',
            options={'ordering': ['-id']},
        ),
    ]
