# Generated by Django 4.2.3 on 2023-07-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newusermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newusermodel',
            options={'ordering': ['-id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
